name: Setup Environment
description: Setup the environment for CI and the version-or-publish workflows

inputs:
  php-version:
    description: The PHP version to install
    default: 8.3

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: xdebug

    - name: Print Libxml Version
      shell: bash
      run: |
        php -r 'echo "libxml: " . LIBXML_DOTTED_VERSION . PHP_EOL;'

    - name: Install Composer Dependencies
      uses: ramsey/composer-install@v3

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
